#include <iostream>
#include <array>
#include <iostream>
#include <string>
#include <array>
#include <vector>
#include <algorithm>
#include <chrono>
#include <ctime>
#include <map>
#include <unordered_map>
#include <iomanip>
#include <iostream>
#include <sstream>
#include <any>
#include <bitset>
#include <assert.h>

#include <fstream>
#include <functional>
#include <chrono>
#include <thread>
#include <tuple>
#include <variant>
#include <any>
#include <iostream>
#include <chrono>
#include <vector>
#include <string>
#include <string>
#include <list>
#include <array>
#include <stack>
#include <queue>
#include <utility>
#include <iomanip>
#include <iostream>
#include <sstream>
#include <any>
#include <optional>